string airfoil_type    # 翼型
string load_type       # 载荷类型
float32 min_velocity   # 最小速度
float32 max_velocity   # 最大速度
float32 max_acceleration   # 最大加速度
float32 max_deceleration   # 最大减速度
float32 max_roll_angle   # 最大滚转角度
float32 max_pitch_angle   # 最大俯仰角度
float32 roll_rate   # 滚转速率
float32 pitch_rate   # 俯仰速率
float32 yaw_rate_to_max_roll   # 最大滚转角度对应的偏航速率
float32 limit_height   # 高度限制
int32 health_point   # 生命值
int32 damage_value   # 伤害值
float32 reconnaissance_radius   # 侦察半径
float32 reconnaissance_angle   # 侦察角度
int32 bombload   # 炸弹载荷
float32 bomb_range   # 炸弹射程 m
float32 bomb_velocity   # 炸弹速度 m/s
float32 bomb_cold_down_time   # 炸弹冷却时间 s